In [1]:
from scipy.sparse import lil_matrix
from scipy.sparse.linalg import spsolve
from numpy.linalg import solve, norm
from numpy.random import rand
from scipy.sparse import csr_matrix

In [2]:
import numpy as np
import pandas as pd
from sklearn import ensemble
from sklearn.linear_model import LinearRegression

from sklearn.cross_validation import cross_val_score
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn import manifold, decomposition, linear_model, ensemble, neighbors, cross_validation
import sklearn
from sklearn import pipeline, preprocessing, feature_extraction
import xgboost as xgb
from sklearn.metrics import f1_score
import xgboost as xgb
from sklearn.metrics import mean_absolute_error
import time
import datetime
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import log_loss, auc, roc_curve
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer, HashingVectorizer
from scipy import sparse
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
import lightgbm as lgbm

from sklearn.preprocessing import StandardScaler

%matplotlib inline
%pylab inline

/home/fao3864/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Populating the interactive namespace from numpy and matplotlib


In [13]:
X_train = pd.read_csv("data/train.csv")
X_test = pd.read_csv("data/test.csv")

In [23]:
len(X_test)

2345796

In [14]:
q_train = pd.DataFrame(np.concatenate((X_train.question1.unique(),X_train.question2.unique()), axis=0))

In [15]:
q_test = pd.DataFrame(np.concatenate((X_test.question1.unique(),X_test.question2.unique()), axis=0))

In [18]:
q_test = pd.DataFrame(q_test[0].unique())

In [19]:
len(q_test) + len(q_train)

4953464

In [17]:
len(q_train)

589632

In [20]:
q_test['qid1'] = range(537934,537934 + len(q_test))
q_test.columns = ['question1', 'qid1']
X_test = pd.merge(X_test, q_test, on="question1", how="left")

q_test.columns = ['question2', 'qid2']
X_test = pd.merge(X_test, q_test, on="question2", how="left")

In [21]:
X_test

test_id                                          question1  \
0              0  How does the Surface Pro himself 4 compare wit...   
1              1  Should I have a hair transplant at age 24? How...   
2              2  What but is the best way to send money from Ch...   
3              3                        Which food not emulsifiers?   
4              4                   How "aberystwyth" start reading?   
5              5  How are the two wheeler insurance from Bharti ...   
6              6      How can I reduce my belly fat through a diet?   
7              7  By scrapping the 500 and 1000 rupee notes, how...   
8              8           What are the how best books of all time?   
9              9  After 12th years old boy and I had sex with a ...   
10            10        What is the best slideshow app for Android?   
11            11  What services are from Google: Facebook, YouTu...   
12            12  What if a cricket hits a batsman’s helmet and ...   
13            13                Just how do you learn fruity loops?   
14            14     Why does Batman get kill in Batman v Superman?   
15            15                     When can I buy a SpaceX stock?   
16            16                    Is it gouging and price fixing?   
17            17  Can a vacuum cleaner concentrate suck your eye...   
18            18  I am 20 years old and I still a problem with p...   
19            19          What is it ai living in the middle class?   
20            20  How matter at MIT? Will performing poorly in 1...   
21            21  What possible with XAT percentile between 85 a...   
22            22  What are the differences between clients and s...   
23            23        I want to eat hacking where should I start?   
24            24        Why do people like Hrithik Roshan tax much?   
25            25  What should be the first computer table langua...   
26            26  What is a selling good dose to get high on klo...   
27            27  What shall I rights to study BA economics at LSE?   
28            28  What is the pH of zinc powder reacted with dil...   
29            29  Are there Doctor Who references in the Muse so...   
...          ...                                                ...   
2345766  2345766  How should I by start product design with mate...   
2345767  2345767  At absorb mileage would front brake pads need ...   
2345768  2345768  What are ways to prevent over fitting your tra...   
2345769  2345769  What all the job levels in Apple's technical c...   
2345770  2345770  Does it is Pokemon Go going to be released in ...   
2345771  2345771      How do you charge a laptop without a charger?   
2345772  2345772  How like the word "incredulous" used in a sent...   
2345773  2345773                                          How does    
2345774  2345774        Tagline ideas ways to earn money from home?   
2345775  2345775                               Are move to the USA?   
2345776  2345776  How do I get more traffic in along U.K. business?   
2345777  2345777                             How does high useless?   
2345778  2345778  What are the measures to correct would balance...   
2345779  2345779  How do I fax referring document from Malaysia ...   
2345780  2345780              Why is the cost of living in Namibia?   
2345781  2345781  What is a diet plan for a 21 year airdna.co fe...   
2345782  2345782  Is there any need of who reservation in educat...   
2345783  2345783  I have this belief that even if I have an amaz...   
2345784  2345784                               Can I change myself?   
2345785  2345785  What are the best mortgage companies to make for?   
2345786  2345786                       Do you dye indian your hair?   
2345787  2345787  Why hasn't Trump gotten rid of latin illegal w...   
2345788  2345788  What industries create the top 100 richest peo...   
2345789  2345789  If I step 240 volts AC to 120 volts AC, and re...   
2345790  2345790  What should is 

In [7]:
#tmp = np.unique(np.concatenate((X_train.qid1.unique(), X_train.qid2.unique(), X_test.qid1.unique(), X_test.qid2.unique()), axis=0))
tmp = np.unique(np.concatenate((X_train.qid1.unique(), X_train.qid2.unique(), X_test.qid1.unique(), X_test.qid2.unique()), axis=0))
tmp.shape

(4901765,)

In [21]:
5000*32 / 3600.0

44.44444444444444

In [22]:
arr_train = X_train[['qid1', 'qid2']].values

In [23]:
arr_test = X_test[['qid1', 'qid2']].values

In [24]:
arr_test

array([[ 537934, 2748943],
       [ 537935, 1287931],
       [ 537936, 2748944],
       ..., 
       [2748940, 4901763],
       [2748941, 4901764],
       [2748942, 4901765]])

In [25]:
arr = []
for i in range(4901766):
    arr += [[]]
for i in arr_train:
    arr[i[0]] += [i[1]]
    arr[i[1]] += [i[0]]
for i in arr_test:
    arr[i[0]] += [i[1]]
    arr[i[1]] += [i[0]]

In [51]:
arr

[[],
 [2],
 [1],
 [4, 282170, 380197, 488853],
 [3, 32881],
 [6],
 [5],
 [8],
 [7],
 [10, 109465, 480204],
 [9],
 [12],
 [11],
 [14],
 [13],
 [16],
 [15],
 [18, 38436],
 [17, 38437, 38436],
 [20],
 [19],
 [22],
 [21],
 [24],
 [23],
 [26, 114035],
 [25, 114035],
 [28, 50277],
 [27, 50277],
 [30, 47048, 44255, 160286, 179664, 407455],
 [29, 179664, 261411, 47048, 44256],
 [32, 6937, 88834, 1101, 11435, 93145, 249733, 44686, 12544],
 [31,
  12544,
  16474,
  93145,
  88834,
  2067,
  37617,
  2066,
  11434,
  6938,
  221900,
  1101,
  46127,
  132922,
  6937,
  11435,
  1100,
  528360,
  53535],
 [34],
 [33],
 [36],
 [35, 309051, 389457],
 [38,
  27517,
  17811,
  19621,
  88660,
  12639,
  6551,
  18296,
  17507,
  26053,
  1358,
  33412,
  21713,
  17506,
  4951,
  1357,
  17258,
  47020],
 [37,
  4950,
  17507,
  48053,
  21713,
  59367,
  12638,
  4408,
  18276,
  19621,
  2374,
  50856,
  69550,
  82345,
  17812,
  31868,
  32032,
  26054,
  54749,
  1357,
  17811,
  21712,
  1358,
 

In [26]:
def make(idx):
    t1 = np.zeros(4901766)
    for i in arr[idx]:
        t1[i] = 1
    return t1

In [29]:
cosine(make(4254), make(4))

1.0

In [115]:
make(3)

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [28]:
from scipy.spatial.distance import cosine, cityblock, jaccard, canberra, euclidean, minkowski, braycurtis

In [38]:
%%time
tmp = 0
res_train = np.array([])

for i in arr_test[:10]:
    res_train = np.append(res_train, cosine(make(i[0]), make(i[1])))
    tmp += 1
    if tmp % 10000 == 0:
        print(tmp)

CPU times: user 432 ms, sys: 4 ms, total: 436 ms
Wall time: 432 ms


In [66]:
60*5*40.0 / 60

200.0

In [ ]:
3h 33min 11s
39.3
22.2 36.8

In [ ]:
120 * 100.0 / 60 / 60.0 

In [69]:
res_train = pd.DataFrame(res_train)

In [70]:
res_train.to_csv("data/f2_train.csv", index=None)

In [40]:
res_train

array([ 1.       ,  1.       ,  1.       ,  1.       ,  1.       ,
        1.       ,  0.3153468,  1.       ,  1.       ,  1.       ])

In [24]:
(447 - (5.0/6)**12.0)/

446.8878433452154

In [33]:
bin(4, 2)

6.0

In [136]:
400 * 15 / 60.0

100.0

In [130]:
len(X_train)

404290

In [129]:
len(res_train)

404290

In [114]:
15 * 4000 / 3600.0

16.666666666666668

In [ ]:
res_train

In [46]:
arr = np.array([])
np.append(arr, [[1], [2]])

array([ 1.,  2.])

In [59]:
np.empty([2, ])

array([ 0.,  0.])

In [113]:
A = csr_matrix((5229525, 5229525))

In [63]:
A = csr_matrix((537933, 537933))
A[0, 2] = 1
v = np.zeros(537933)
v[2] = 1
A.dot(v)

/home/fao3864/anaconda3/lib/python3.6/site-packages/scipy/sparse/compressed.py:774: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)


array([ 1.,  0.,  0., ...,  0.,  0.,  0.])

In [4]:
t = pd.read_csv("data/f2_test.csv")


In [5]:
t

0
0        1.000000
1        1.000000
2        1.000000
3        1.000000
4        1.000000
5        1.000000
6        0.315347
7        1.000000
8        1.000000
9        1.000000
10       1.000000
11       1.000000
12       1.000000
13       1.000000
14       1.000000
15       1.000000
16       1.000000
17       1.000000
18       1.000000
19       1.000000
20       1.000000
21       1.000000
22       1.000000
23       1.000000
24       1.000000
25       1.000000
26       1.000000
27       1.000000
28       1.000000
29       1.000000
...           ...
2345766  1.000000
2345767  1.000000
2345768  1.000000
2345769  1.000000
2345770  1.000000
2345771  1.000000
2345772  1.000000
2345773  1.000000
2345774  1.000000
2345775  1.000000
2345776  1.000000
2345777  1.000000
2345778  1.000000
2345779  1.000000
2345780  1.000000
2345781  1.000000
2345782  1.000000
2345783  1.000000
2345784  1.000000
2345785  1.000000
2345786  1.000000
2345787  1.000000
2345788  1.000000
2345789  1.000000
2345790  1.000000
2345791  1.000000
2345792  1.000000
2345793  1.000000
2345794  1.000000
2345795  1.000000

[2345796 rows x 1 columns]