In [1]:
import numpy as np
import pandas as pd
from sklearn import ensemble
from sklearn.linear_model import LinearRegression

from sklearn.cross_validation import cross_val_score
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn import manifold, decomposition, linear_model, ensemble, neighbors, cross_validation
import sklearn
from sklearn import pipeline, preprocessing, feature_extraction
import xgboost as xgb
from sklearn.metrics import f1_score
import xgboost as xgb
from sklearn.metrics import mean_absolute_error
import time
import datetime
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import log_loss, auc, roc_curve
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer, HashingVectorizer
from scipy import sparse
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
import lightgbm as lgbm

from sklearn.preprocessing import StandardScaler

%matplotlib inline
%pylab inline

Populating the interactive namespace from numpy and matplotlib


/home/fao3864/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
X_train = pd.read_csv("data/train.csv")
X_test = pd.read_csv("data/test.csv")

y_train = pd.DataFrame(X_train['is_duplicate'])
y_train.columns = ['y']
del X_train['is_duplicate']

skf = StratifiedKFold(5, shuffle=True, random_state=0)
folds = []
for itr, ite in skf.split(X_train, y_train.y):
    folds += [[itr, ite]]

In [3]:
X_train = pd.read_csv("data/train_inter.csv")

X_train['question1'] = X_train['question1'].apply(lambda x: str(x))
X_train['question2'] = X_train['question2'].apply(lambda x: str(x))

X_train['question1'] = X_train['question1'].apply(lambda x: x.lower().split())
X_train['question2'] = X_train['question2'].apply(lambda x: x.lower().split())



In [4]:
X_test = pd.read_csv("data/test_inter.csv")

X_test['question1'] = X_test['question1'].apply(lambda x: str(x))
X_test['question2'] = X_test['question2'].apply(lambda x: str(x))

X_test['question1'] = X_test['question1'].apply(lambda x: x.lower().split())
X_test['question2'] = X_test['question2'].apply(lambda x: x.lower().split())

In [5]:
X = map(lambda x: ' '.join(x), X_train['question1'])
X1 = map(lambda x: ' '.join(x), X_train['question2'])
Y = map(lambda x: ' '.join(x), X_test['question1'])
Y1 = map(lambda x: ' '.join(x), X_test['question2'])

hw = HashingVectorizer(n_features=200).fit(X_train['question1'] + X_train['question2'])


In [6]:
X = pd.DataFrame(hw.transform(X).todense())
X1 = pd.DataFrame(hw.transform(X1).todense())
Y = pd.DataFrame(hw.transform(Y).todense())
Y1 = pd.DataFrame(hw.transform(Y1).todense())

In [7]:
tfidf = feature_extraction.text.TfidfTransformer()
tfidf.fit(X+X1)

X = pd.DataFrame(tfidf.transform(X).todense())
X1 = pd.DataFrame(tfidf.transform(X1).todense())
Y = pd.DataFrame(tfidf.transform(Y).todense())
Y1 = pd.DataFrame(tfidf.transform(Y1).todense())

In [8]:
X_train = pd.concat([X_train, X], axis=1, join_axes=[X_train.index])
del X
X_train = pd.concat([X_train, X1], axis=1, join_axes=[X_train.index])
del X1
X_test = pd.concat([X_test, Y], axis=1, join_axes=[X_test.index])
del Y
X_test = pd.concat([X_test, Y1], axis=1, join_axes=[X_test.index])
del Y1

In [31]:
X_train[:2]

id  qid1  qid2                                          question1  \
0   0     1     2  [what, is, the, step, by, step, guide, to, inv...   
1   1     3     4  [what, is, the, story, of, kohinoor, (koh-i-no...   

                                           question2  word_match  \
0  [what, is, the, step, by, step, guide, to, inv...    0.727273   
1  [what, would, happen, if, the, indian, governm...    0.307692   

   tfidf_word_match    0    1    2 ...   190  191       192  193  194  195  \
0          0.772164  0.0  0.0  0.0 ...   0.0  0.0  0.325385  0.0  0.0  0.0   
1          0.361758  0.0  0.0  0.0 ...   0.0  0.0  0.000000  0.0  0.0  0.0   

   196  197  198  199  
0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  

[2 rows x 407 columns]

In [9]:
del X_train['question1']
del X_train['question2']
del X_train['qid1']
del X_train['qid2']
del X_train['id']

del X_test['question1']
del X_test['question2']
del X_test['test_id']

In [10]:
#tmp = abs(X_train.ix[:, 2:202] * X_train.ix[:, -200:])
#X_train = pd.concat([X_train, tmp], axis=1, join_axes=[X_train.index])
tmp = abs(X_train.ix[:, 2:202] - X_train.ix[:, -200:])
X_train = pd.concat([X_train, tmp], axis=1, join_axes=[X_train.index])

#tmp = abs(X_test.ix[:, 2:202] * X_test.ix[:, -200:])
#X_test = pd.concat([X_test, tmp], axis=1, join_axes=[X_test.index])
tmp = abs(X_test.ix[:, 2:202] - X_test.ix[:, -200:])
X_test = pd.concat([X_test, tmp], axis=1, join_axes=[X_test.index])

In [11]:
del tmp

In [13]:
#X_train = pd.read_csv("data/train_inter.csv")
q_train = pd.read_csv("data/freq_train.csv")
X_train = pd.concat([X_train, q_train], axis=1)

f_train = pd.read_csv("data/train_features.csv", encoding = "ISO-8859-1")
f_train = f_train.ix[:, 2:]
X_train = pd.concat([X_train, f_train], axis=1)

In [14]:
X_train[:2]

word_match  tfidf_word_match    0    1    2    3    4    5    6    7  \
0    0.727273          0.772164  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1    0.307692          0.361758  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

     ...      cityblock_distance  jaccard_distance  canberra_distance  \
0    ...                5.081614               1.0          94.023324   
1    ...               14.195119               1.0         177.588090   

   euclidean_distance  minkowski_distance  braycurtis_distance  skew_q1vec  \
0            0.371408            0.168999             0.186557    0.031817   
1            1.012091            0.455910             0.592655    0.008735   

   skew_q2vec  kur_q1vec  kur_q2vec  
0   -0.091902   0.050416   0.337301  
1    0.094704   0.284010  -0.034444  

[2 rows x 632 columns]

In [37]:
del f_test

In [42]:
import gc
gc.collect()

195

In [31]:
q_test = pd.read_csv("data/freq_test.csv")


In [32]:
X_test = pd.concat([X_test, q_test], axis=1)

In [35]:
f_test = pd.read_csv("data/test_features.csv", encoding = "ISO-8859-1")
f_test = f_test.ix[:, 2:]

In [36]:
X_test = pd.concat([X_test, f_test], axis=1)

In [39]:
X_test[:2]

word_match  tfidf_word_match    0    1    2    3    4         5    6    7  \
0    0.266667          0.274019  0.0  0.0  0.0  0.0  0.0 -0.156312  0.0  0.0   
1    0.500000          0.480962  0.0  0.0  0.0  0.0  0.0 -0.164904  0.0  0.0   

     ...      cityblock_distance  jaccard_distance  canberra_distance  \
0    ...               12.006720               1.0         164.254264   
1    ...                6.501658               1.0         115.512012   

   euclidean_distance  minkowski_distance  braycurtis_distance  skew_q1vec  \
0            0.889327            0.407153             0.483565    0.045990   
1            0.466698            0.210239             0.245248   -0.017419   

   skew_q2vec  kur_q1vec  kur_q2vec  
0    0.009958   0.039938  -0.144866  
1   -0.046821   0.207580  -0.042937  

[2 rows x 632 columns]

In [18]:
param = {}
param['objective'] = 'binary:logistic'
param['eval_metric'] = 'logloss'
param['max_depth'] = 7
# param['booster'] = 'dart'
#param['booster'] = 'gblinear'
param['eta'] = 0.1
#param['subsample'] = 1.0
# param["scale_pos_weight"] = 0.5
#param['colsample_bytree'] = 0.7
param['nthread'] = 8
#param['num_class'] =3
#param['alpha'] = 0.00
#param['lambda_bias'] = 0.1
# param['lambda'] = 0
#param['min_child_weight'] = 100

# if param['booster'] == 'gblinear': param['eta'] *= 1e-4
numround = 2000

#LGBM
params = {
    #'task': 'train',
    #'boosting_type': 'gbdt',
    #'objective': 'regression',
    #'metric': {'l2', 'auc'},
    #'num_leaves': 31,
    #'feature_fraction': 0.9,
    #'bagging_fraction': 0.8,
    #'bagging_freq': 5,
    #'subsample': 0.8,
    #'colsample_bytree': 0.7,
    'objective': 'binary',
    'nthread': -1,
    'learning_rate': 0.1,
    'min_child_weight': 5,
    #'max_depth': 6
    #'num_class': 3
    
}

pred_train = np.zeros(len(y_train))
xgbs = []
sc,sc_mean = [],[]

for itr, ite in folds:
    ypred = []
    for i in range(1):
               
        param['seed'] = i+1
        
        #xgboost
        
        Xdatatrain = xgb.DMatrix(data=X_train.ix[itr, :].values,
                                     label=y_train.ix[itr].values)
        Xdataval = xgb.DMatrix(data=X_train.ix[ite, :].values,
                                     label=y_train.ix[ite].values)

        plst = list(param.items())
        watchlist = [(Xdatatrain, 'train'), (Xdataval, 'eval')]
        bst = xgb.train(plst, Xdatatrain, numround, evals=watchlist, verbose_eval=15)

        
        #rc = ensemble.ExtraTreesClassifier(n_estimators=1300, criterion='gini', max_depth=None, n_jobs=-1)
        #pred_train[ite] = bst.predict(Xdataval)
        #neigh = KNeighborsClassifier(n_neighbors=2)
        #neigh.fit(X_train.ix[itr, :], y_train.ix[itr])
        ypred = bst.predict(Xdataval)
        #ypred = neigh.predict_proba(X_train.ix[ite, :])
        xgbs.append(bst)
        '''
        
        # train
        lgb = lgbm.sklearn.LGBMClassifier(n_estimators=300, seed=0, **params)
        lgb.fit(X_train.ix[itr, :], y_train.ix[itr])
        ypred = lgb.predict_proba(X_train.ix[ite, :])[:, 1]

        
        model.fit(X_train.ix[itr, :].values, y_train_cat[itr],
            epochs=60,
            batch_size=1000)
        ypred = model.predict(X_train.ix[ite, :].values)
        '''
    #ypred = sum(ypred) / len(ypred) 0.401408 0.392476
    pred_train[ite] = ypred
    
    
    sc.append(log_loss(y_train.ix[ite, :], pred_train[ite]))

    
print('XGB: {:.3f} +- {:.3f}'.format(np.mean(sc), np.std(sc)))

[0]	train-logloss:0.642997	eval-logloss:0.64345
[15]	train-logloss:0.37954	eval-logloss:0.383378
[30]	train-logloss:0.332223	eval-logloss:0.338569
[45]	train-logloss:0.316031	eval-logloss:0.324481
[60]	train-logloss:0.305652	eval-logloss:0.316564
[75]	train-logloss:0.298584	eval-logloss:0.311831
[90]	train-logloss:0.292458	eval-logloss:0.308071
[105]	train-logloss:0.288224	eval-logloss:0.305941
[120]	train-logloss:0.283713	eval-logloss:0.303657
[135]	train-logloss:0.27987	eval-logloss:0.301569
[150]	train-logloss:0.276814	eval-logloss:0.300182
[165]	train-logloss:0.273626	eval-logloss:0.298764
[180]	train-logloss:0.27081	eval-logloss:0.297738
[195]	train-logloss:0.268143	eval-logloss:0.296692
[210]	train-logloss:0.265937	eval-logloss:0.295938
[225]	train-logloss:0.263986	eval-logloss:0.295282
[240]	train-logloss:0.262043	eval-logloss:0.294575
[255]	train-logloss:0.260151	eval-logloss:0.293854
[270]	train-logloss:0.257907	eval-logloss:0.293062
[285]	train-logloss:0.25597	eval-logloss:0.

In [40]:
def foo(x):
    a = 0.165 / 0.37
    b = (1 - 0.165) / (1 - 0.37) 
    return  a * x / (a * x + b * (1 - x))

In [20]:
pred_train = foo(pred_train)

In [21]:
pred_train = pd.DataFrame(pred_train)
pred_train.columns = ['y']
pred_train.to_csv("stacking/xgb_15.csv", index=None)

In [56]:
submit = pd.read_csv("data/sample_submission.csv")

In [43]:
lgb = lgbm.sklearn.LGBMClassifier(n_estimators=300, seed=0, **params)
lgb.fit(X_train, y_train)


/home/fao3864/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:112: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/fao3864/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:147: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LGBMClassifier(boosting_type='gbdt', colsample_bytree=1, drop_rate=0.1,
        is_unbalance=False, learning_rate=0.1, max_bin=255, max_depth=-1,
        max_drop=50, min_child_samples=10, min_child_weight=5,
        min_split_gain=0, n_estimators=300, nthread=-1, num_leaves=31,
        objective='binary', reg_alpha=0, reg_lambda=0, scale_pos_weight=1,
        seed=0, sigmoid=1.0, silent=True, skip_drop=0.5, subsample=1,
        subsample_for_bin=50000, subsample_freq=1, uniform_drop=False,
        xgboost_dart_mode=False)

In [142]:
X_test = X_test.ix[1000001:, :]

In [145]:
test_pred2 = lgb.predict_proba(X_test)[:, 1]

In [126]:
test_pred1[:4]

array([ 0.00778551,  0.58706412,  0.45319938,  0.00166404])

In [127]:
test_pred1[-4:]

array([  4.85291907e-04,   2.61291438e-01,   6.26312391e-01,
         1.66797416e-03])

In [149]:
test_pred2[:4]

array([  3.51530930e-01,   3.07114939e-04,   1.03535362e-03,
         9.95933188e-02])

In [151]:
test_pred2[-4:]

array([  1.67587699e-03,   2.31711933e-04,   3.72899384e-01,
         3.89707027e-01])

In [148]:
len(test_pred1)

1000001

In [152]:
len(test_pred2)

1345795

In [153]:
test_pred = np.concatenate([test_pred1, test_pred2], axis=0)

In [154]:
len(test_pred)

2345796

In [155]:
test_pred

array([  7.78551300e-03,   5.87064116e-01,   4.53199376e-01, ...,
         2.31711933e-04,   3.72899384e-01,   3.89707027e-01])

In [146]:
del pred_train

NameError: name 'pred_train' is not defined

In [51]:
import gc
gc.collect()

0

In [19]:
param = {}
param['objective'] = 'binary:logistic'
param['eval_metric'] = 'logloss'
param['max_depth'] = 7
# param['booster'] = 'dart'
#param['booster'] = 'gblinear'
param['eta'] = 0.1
#param['subsample'] = 1.0
# param["scale_pos_weight"] = 0.5
#param['colsample_bytree'] = 0.7
param['nthread'] = 8
#param['num_class'] =3
#param['alpha'] = 0.00
#param['lambda_bias'] = 0.1
# param['lambda'] = 0
#param['min_child_weight'] = 100

# if param['booster'] == 'gblinear': param['eta'] *= 1e-4
numround = 2000

In [20]:
Xdatatrain = xgb.DMatrix(data=X_train.ix[:, :].values,
                                     label=y_train.ix[:].values)

In [21]:
Xdataval = xgb.DMatrix(data=X_train.ix[:10, :].values,
                                     label=y_train.ix[:10].values)

In [47]:
del X_test

In [46]:
Xdatatest2 = xgb.DMatrix(data=X_test.ix[1000001:, :].values)

In [23]:

plst = list(param.items())
watchlist = [(Xdatatrain, 'train'), (Xdataval, 'eval')]

In [25]:
bst = xgb.train(plst, Xdatatrain, numround, evals=watchlist, verbose_eval=15)


[0]	train-logloss:0.643077	eval-logloss:0.634047
[15]	train-logloss:0.37953	eval-logloss:0.419373
[30]	train-logloss:0.3323	eval-logloss:0.390615
[45]	train-logloss:0.317464	eval-logloss:0.393716
[60]	train-logloss:0.308375	eval-logloss:0.389183
[75]	train-logloss:0.300855	eval-logloss:0.401466
[90]	train-logloss:0.295579	eval-logloss:0.383456
[105]	train-logloss:0.291515	eval-logloss:0.386859
[120]	train-logloss:0.287283	eval-logloss:0.385894
[135]	train-logloss:0.283842	eval-logloss:0.378404
[150]	train-logloss:0.280634	eval-logloss:0.377714
[165]	train-logloss:0.278092	eval-logloss:0.373746
[180]	train-logloss:0.275286	eval-logloss:0.37967
[195]	train-logloss:0.27285	eval-logloss:0.373462
[210]	train-logloss:0.269792	eval-logloss:0.372048
[225]	train-logloss:0.267772	eval-logloss:0.378358
[240]	train-logloss:0.265629	eval-logloss:0.377458
[255]	train-logloss:0.263883	eval-logloss:0.373124
[270]	train-logloss:0.261896	eval-logloss:0.365807
[285]	train-logloss:0.260195	eval-logloss:0.

In [52]:
test_pred2 = bst.predict(Xdatatest2)


In [49]:
test_pred1[:4]

array([  2.29527755e-03,   5.45756638e-01,   6.37812853e-01,
         4.23383579e-04], dtype=float32)

In [50]:
len(test_pred1)

1000001

In [53]:
test_pred1[:4]

array([  2.29527755e-03,   5.45756638e-01,   6.37812853e-01,
         4.23383579e-04], dtype=float32)

In [54]:
test_pred = np.concatenate([test_pred1, test_pred2], axis=0)

In [55]:
len(test_pred)

2345796

In [57]:
test_pred = foo(test_pred)

In [58]:
submit['is_duplicate'] = test_pred

In [59]:
submit.to_csv("stacking/xgb_15_test.csv", index=None)

In [161]:
submit

test_id  is_duplicate
0              0      0.002633
1              1      0.323567
2              2      0.218058
3              3      0.000561
4              4      0.095342
5              5      0.007831
6              6      0.956379
7              7      0.098221
8              8      0.363882
9              9      0.002275
10            10      0.423677
11            11      0.000240
12            12      0.000097
13            13      0.034839
14            14      0.033894
15            15      0.020784
16            16      0.000108
17            17      0.392933
18            18      0.150615
19            19      0.284470
20            20      0.000149
21            21      0.018111
22            22      0.004705
23            23      0.004349
24            24      0.000205
25            25      0.061033
26            26      0.000158
27            27      0.009628
28            28      0.099425
29            29      0.000419
...          ...           ...
2345766  2345766      0.000039
2345767  2345767      0.000291
2345768  2345768      0.023880
2345769  2345769      0.000088
2345770  2345770      0.063847
2345771  2345771      0.446460
2345772  2345772      0.089966
2345773  2345773      0.000060
2345774  2345774      0.001341
2345775  2345775      0.276473
2345776  2345776      0.032203
2345777  2345777      0.009648
2345778  2345778      0.000300
2345779  2345779      0.009260
2345780  2345780      0.000238
2345781  2345781      0.058332
2345782  2345782      0.088220
2345783  2345783      0.000379
2345784  2345784      0.418718
2345785  2345785      0.000115
2345786  2345786      0.000045
2345787  2345787      0.000076
2345788  2345788      0.011994
2345789  2345789      0.000081
2345790  2345790      0.000093
2345791  2345791      0.000088
2345792  2345792      0.000564
2345793  2345793      0.000078
2345794  2345794      0.166718
2345795  2345795      0.176853

[2345796 rows x 2 columns]